version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: willitmod-axesim_server_1
      APP_PORT: 8081

  server:
    image: ghcr.io/willitmod/axesim-release:v1.0.7@sha256:d4c3203d50232795e04bc6cebc4ba949ea0cd871e1bf86c8ea12d3d1434f0eef
    restart: on-failure
    stop_grace_period: 30s
    init: true
    ports:
      - "8801-8810:8801-8810"
    environment:
      AXESIM_HOME: /data
      AXESIM_PORT: 8081
      AXESIM_HOST: 0.0.0.0
      AXESIM_PUBLISH_MINERS: 1
      AXESIM_PUBLISH_HOST: 0.0.0.0
      AXESIM_PUBLISH_START_PORT: 8801
      AXESIM_PUBLISH_COUNT: 10
    volumes:
      - ${APP_DATA_DIR}/data:/data
