version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: willitmod-axesim_server_1
      APP_PORT: 8081

  server:
    image: ghcr.io/willitmod/axesim-release:v1.0.5@sha256:3a4693a96422ec0a01bca3e7dada4843b7ae62e2f839437e1b6dc42218472c64
    restart: on-failure
    stop_grace_period: 30s
    init: true
    ports:
      - "8801-8810:8801-8810"
    environment:
      AXESIM_HOME: /data
      AXESIM_PORT: 8081
      AXESIM_HOST: 0.0.0.0
    volumes:
      - ${APP_DATA_DIR}/data:/data
