version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: willitmod-axebench_server_1
      APP_PORT: 5000

  server:
    image: ghcr.io/willitmod/axebench:v3.0.29
    restart: on-failure
    stop_grace_period: 30s
    init: true
    environment:
      AXE_HOST: 0.0.0.0
      AXE_PORT: 5000
      HOME: /data
    volumes:
      - ${APP_DATA_DIR}/data:/data
