version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: willitmod-axebench_server_1
      APP_PORT: 5000

  server:
    image: ghcr.io/willitmod/axebench-release:v3.0.2-r1
    restart: on-failure
    stop_grace_period: 30s
    init: true
    ports:
      - "5000:5000"
    environment:
      AXE_HOST: 0.0.0.0
      AXE_PORT: 5000
      HOME: /data
    volumes:
      - ${APP_DATA_DIR}/data:/data
